openapi: 3.0.0
info:
  title: Petclinic API
  description: API documentation for Petclinic
  version: '1.0'
servers:
  - url: https://petclinic.example.com
paths:
  /owners/new:
    get:
      summary: Initiate creation of a new owner
      operationId: initCreationForm
      responses:
        '200':
          description: Show owner creation form
    post:
      summary: Process creation of a new owner
      operationId: processCreationForm
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Owner'
      responses:
        '302':
          description: Redirect to the owner's details page after creation
  /owners/find:
    get:
      summary: Initiate find owner form
      operationId: initFindForm
      responses:
        '200':
          description: Show find owner form
  /owners:
    get:
      summary: Process the search for owners by last name
      operationId: processFindForm
      parameters:
        - name: lastName
          in: query
          description: The last name of the owner to search for
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Show owners list or redirect if only one result found
  /owners/{ownerId}/edit:
    get:
      summary: Initiate update owner form
      operationId: initUpdateOwnerForm
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Show owner update form
    post:
      summary: Process update of an owner's information
      operationId: processUpdateOwnerForm
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Owner'
      responses:
        '302':
          description: Redirect to the owner's details page after update
  /owners/{ownerId}:
    get:
      summary: Display an owner's details
      operationId: showOwner
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Show owner details page
components:
  schemas:
    Owner:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        city:
          type: string
        telephone:
          type: string
      required:
        - firstName
        - lastName
        - address
        - city
        - telephone