openapi: 3.0.0
info:
  title: Petclinic Pet API
  version: '1.0'
servers:
  - url: 'https://petclinic.example.com'
paths:
  /owners/{ownerId}/pets/new:
    get:
      summary: Initiate creation of a new pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pet creation form
    post:
      summary: Process creation of a new pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '302':
          description: Redirect to the owner's page with the new pet
  /owners/{ownerId}/pets/{petId}/edit:
    get:
      summary: Initiate update of a pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pet update form
    post:
      summary: Process update of a pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '302':
          description: Redirect to the owner's page with the updated pet
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        birthDate:
          type: string
          format: date
        type:
          $ref: '#/components/schemas/PetType'
        owner:
          $ref: '#/components/schemas/Owner'
      required:
        - name
        - birthDate
        - type
    PetType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - name
    Owner:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        city:
          type: string
        telephone:
          type: string
      required:
        - firstName
        - lastName
        - address
        - city
        - telephone