openapi: 3.0.0
info:
  title: Petclinic Vet API
  version: '1.0'
servers:
  - url: 'https://petclinic.example.com'
paths:
  /vets:
    get:
      summary: Show vet list
      responses:
        '200':
          description: List of vets
  /vets.json:
    get:
      summary: Show vet list in JSON format
      responses:
        '200':
          description: List of vets in JSON format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vets'
  /vets.xml:
    get:
      summary: Show vet list in XML format
      responses:
        '200':
          description: List of vets in XML format
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Vets'
components:
  schemas:
    Vet:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        specialties:
          type: array
          items:
            $ref: '#/components/schemas/Specialty'
      required:
        - firstName
        - lastName
    Specialty:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - name
    Vets:
      type: object
      properties:
        vetList:
          type: array
          items:
            $ref: '#/components/schemas/Vet'
