openapi: 3.0.0
info:
  title: Petclinic Visit API
  version: '1.0'
servers:
  - url: 'https://petclinic.example.com'
paths:
  /owners/*/pets/{petId}/visits/new:
    get:
      summary: Initiate creation of a new visit
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Visit creation form
    post:
      summary: Process creation of a new visit
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Visit'
      responses:
        '302':
          description: Redirect to the owner's page
  /owners/*/pets/{petId}/visits:
    get:
      summary: Show visits for a pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of visits for the pet
components:
  schemas:
    Visit:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        description:
          type: string
        pet:
          $ref: '#/components/schemas/Pet'
      required:
        - date
        - description
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        birthDate:
          type: string
          format: date
        type:
          $ref: '#/components/schemas/PetType'
        owner:
          $ref: '#/components/schemas/Owner'
      required:
        - name
        - birthDate
        - type
    PetType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - name
    Owner:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        city:
          type: string
        telephone:
          type: string
      required:
        - firstName
        - lastName
        - address
        - city
        - telephone