openapi: 3.0.0
info:
  title: Spring PetClinic API
  description: API documentation for Spring PetClinic
  version: '1.0'
servers:
  - url: 'https://petclinic.example.com'
paths:
  /owners/new:
    get:
      summary: Initiate creation of a new owner
      responses:
        '200':
          description: Owner creation form
    post:
      summary: Process creation of a new owner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Owner'
      responses:
        '302':
          description: Redirect to owner details
  /owners/find:
    get:
      summary: Initiate owner search
      responses:
        '200':
          description: Owner search form
  /owners:
    get:
      summary: Process owner search or list all owners
      parameters:
        - name: lastName
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of owners or owner search results
  /owners/{ownerId}/edit:
    get:
      summary: Initiate update of an existing owner
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Owner update form
    post:
      summary: Process update of an existing owner
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Owner'
      responses:
        '302':
          description: Redirect to updated owner details
  /owners/{ownerId}:
    get:
      summary: Display an owner by ID
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Owner details
  /owners/{ownerId}/pets/new:
    get:
      summary: Initiate creation of a new pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pet creation form
    post:
      summary: Process creation of a new pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '302':
          description: Redirect to owner details
  /owners/{ownerId}/pets/{petId}/edit:
    get:
      summary: Initiate update of an existing pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pet update form
    post:
      summary: Process update of an existing pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '302':
          description: Redirect to updated pet details
  /vets:
    get:
      summary: Show vet list
      responses:
        '200':
          description: Vet list page
  /vets.json:
    get:
      summary: Show vet list in JSON format
      responses:
        '200':
          description: JSON list of vets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vets'
  /vets.xml:
    get:
      summary: Show vet list in XML format
      responses:
        '200':
          description: XML list of vets
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Vets'
components:
  schemas:
    Owner:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        city:
          type: string
        telephone:
          type: string
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        birthDate:
          type: string
          format: date
        type:
          $ref: '#/components/schemas/PetType'
    PetType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Vets:
      type: object
      properties:
        vetList:
          type: array
          items:
            $ref: '#/components/schemas/Vet'
    Vet:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        specialties:
          type: array
          items:
            $ref: '#/components/schemas/Specialty'
    Specialty:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
