openapi: 3.0.0
info:
  title: Spring PetClinic API
  description: API documentation for Spring PetClinic
  version: '1.0'
servers:
  - url: 'https://petclinic.example.com'
paths:
  /owners/new:
    get:
      summary: Initiate creation of a new owner
      responses:
        '200':
          description: Owner creation form
    post:
      summary: Process creation of a new owner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Owner'
      responses:
        '302':
          description: Redirect to owner details
  /owners/find:
    get:
      summary: Initiate owner search
      responses:
        '200':
          description: Owner search form
  /owners:
    get:
      summary: Process owner search or list all owners
      parameters:
        - name: lastName
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of owners or owner search results
  /owners/{ownerId}/edit:
    get:
      summary: Initiate update of an existing owner
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Owner update form
    post:
      summary: Process update of an existing owner
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Owner'
      responses:
        '302':
          description: Redirect to updated owner details
  /owners/{ownerId}:
    get:
      summary: Display an owner by ID
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Owner details
components:
  schemas:
    Owner:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        city:
          type: string
        telephone:
          type: string
