openapi: 3.0.0
info:
  title: Spring PetClinic API
  description: API documentation for Spring PetClinic
  version: '1.0'
servers:
  - url: 'https://petclinic.example.com'
paths:
  /owners/{ownerId}/pets/new:
    get:
      summary: Initiate creation of a new pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pet creation form
    post:
      summary: Process creation of a new pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '302':
          description: Redirect to owner details
  /owners/{ownerId}/pets/{petId}/edit:
    get:
      summary: Initiate update of an existing pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pet update form
    post:
      summary: Process update of an existing pet
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '302':
          description: Redirect to updated pet details
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        birthDate:
          type: string
          format: date
        type:
          $ref: '#/components/schemas/PetType'
    PetType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
