openapi: 3.0.0
info:
  title: Spring PetClinic API
  description: API documentation for Spring PetClinic
  version: '1.0'
servers:
  - url: 'https://petclinic.example.com'
paths:
  /vets:
    get:
      summary: Show vet list
      responses:
        '200':
          description: Vet list page
  /vets.json:
    get:
      summary: Show vet list in JSON format
      responses:
        '200':
          description: JSON list of vets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vets'
  /vets.xml:
    get:
      summary: Show vet list in XML format
      responses:
        '200':
          description: XML list of vets
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Vets'
components:
  schemas:
    Vets:
      type: object
      properties:
        vetList:
          type: array
          items:
            $ref: '#/components/schemas/Vet'
    Vet:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        specialties:
          type: array
          items:
            $ref: '#/components/schemas/Specialty'
    Specialty:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
